#!/bin/sh
# Return the terminal emulator that this shell is running in. With no argument return the command line that
# was used to start the terminal emulator, with a single arg of "comm" return the name of the terminal emulator
# Code thanks to this stackexchange thread:
#  https://unix.stackexchange.com/questions/170428/identify-whether-terminal-is-open-in-guake/610413#610413
set -f
pid=$PPID
my_tty=$(ps -p $$ -o tty=)
arg=${1:-args}
while
  [ "$pid" -ne 1 ] &&
  set -- $(ps -p "$pid" -o ppid= -o tty= -o ${arg}=) &&
  [ "$2" = "$my_tty" ]
do
    pid=$1
done

case "$3" in
    *tmux*)
	tmuxpid=$(tmux display-message -p "#{client_pid}")
	printf '%s\n' "$(ps -p $(ps -p $(ps -p $tmuxpid -o sid=) -o ppid=) -o ${arg}=)" ;;
    *)
	shift; shift
	printf '%s\n' "$*";;
esac

